name: doc

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt -r requirements/docs.txt

    - name: Build sphinx documentation
      run: |
        python setup.py build_docs
        # notify github this isn't a jekyll site
        touch build/sphinx/html/.nojekyll

    - name: Deploy docs to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build/sphinx/html
        single-commit: true
