name: release

on:
  push:
    branches: [deploy]
    tags: [v*]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build ".[test,doc]"

    - name: Test with pytest
      env:
        PY_COLORS: 1 # forcibly enable pytest colors
      run: pytest

    - name: Build sdist
      run: |
        git clean -fxd
        make man
        make sdist

    - name: Build wheel
      run: make wheel

    - name: Output dist file info
      run: |
        sha512sum dist/*
        tar -ztf dist/*.tar.gz | sort

    - name: Install twine and check files
      run: |
        pip install twine wheel-inspect
        twine check dist/*
        wheel2json dist/*.whl

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      run: twine upload dist/*

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*.tar.gz
        fail_on_unmatched_files: true
